version: '3.8'

services:

  db_banco:
    image: postgres:15
    container_name: meu_postgres_pro
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dados_banco:/var/lib/postgresql/data

  adminer_gui:
    image: adminer
    container_name: meu_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db_banco

  website:
    image: nginx:alpine
    container_name: meu_site_institucional
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./site:/usr/share/nginx/html
